# Generated by Django 3.2 on 2021-04-23 20:59

from django.db import migrations, models
import django.db.models.deletion
import foodbornePathogen.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=foodbornePathogen.models.getUserDir)),
                ('seqReadsAvailable', models.BooleanField(default=False)),
                ('assembliesAvailable', models.BooleanField(default=False)),
                ('genesAvailable', models.BooleanField(default=False)),
                ('annotationsAvailable', models.BooleanField(default=False)),
                ('analysesAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('pipeRange', models.PositiveSmallIntegerField(choices=[(0, 'Full Pipeline'), (1, 'Genome Assembly'), (2, 'Gene Prediction'), (3, 'Functional Annotation'), (4, 'Comparative Genomics'), (5, 'GA - GP'), (6, 'GA - FA'), (7, 'GP - FA'), (8, 'GP - CG'), (9, 'FA - CG')])),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbornePathogen.job')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CGStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodbornePathogen.stage')),
            ],
            bases=('foodbornePathogen.stage',),
        ),
        migrations.CreateModel(
            name='FAStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodbornePathogen.stage')),
            ],
            bases=('foodbornePathogen.stage',),
        ),
        migrations.CreateModel(
            name='GAStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodbornePathogen.stage')),
                ('reconFlag', models.BooleanField(default=False)),
                ('cut_mean_quality', models.PositiveSmallIntegerField(default=28)),
                ('average_qual', models.PositiveSmallIntegerField(default=28)),
                ('cut_window_size', models.PositiveSmallIntegerField(default=20)),
                ('kmer_size', models.PositiveSmallIntegerField(default=21)),
                ('min_block_size', models.PositiveSmallIntegerField(default=10)),
                ('block_coverage_threshold', models.FloatField(default=0.75)),
            ],
            bases=('foodbornePathogen.stage',),
        ),
        migrations.CreateModel(
            name='GPStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodbornePathogen.stage')),
            ],
            bases=('foodbornePathogen.stage',),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbornePathogen.isolate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbornePathogen.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbornePathogen.user'),
        ),
        migrations.AddField(
            model_name='isolate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodbornePathogen.user'),
        ),
    ]
